# site settings

title: Sanchit Sabhlok
description: Personal Website
taglong: Postdoctoral Researcher at University of Arizona
tagshort: Postdoc @ UofA
url: https://sanchitsabhlok.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/sanchitsabhlok/sanchitsabhlok.github.io

# author settings


author: 
  name: Sanchit Sabhlok
  email: ssabhlok@ucsd.edu
photo: /assets/jpg/ssabhlok.jpg

# social media links

social:
  github: sanchitsabhlok
  orcid: 0000-0002-8780-8226
  ads: sanchit.sabhlok
#  stackoverflow: 0000000/username
#  twitter: username

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
